stages:
- name: compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: ./mvnw package
- name: run
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: java -jar target/*.jar
timeout: 60
notification: {}
